### ISSUE TITLE
サービスをクローズする

### ISSUE THREAD

**Issue by PharaohKJ** [50river/holiday_doctor#19]
@50river さん、もう休日当番医情報がまったく更新されていないようです。
本家サイトも別サイトに誘導されるみたいですし。

http://i-search.pref.ishikawa.jp/toban/index.php?a=3

今、毎朝、このページを更新するという作業 ( gh-pages のブランチを伸ばす )を自動でしているのですが、
止めてしまいたいと思います。

いかがでしょう？

**Comment by 50river** [comment]
closeしましょう。
